version: '3'
services:
  web:
    image: prodbackend
    build: .
    command: "npm start"
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - /prodata:/data/db