export interface req {
  id: String,
  reqname: String,
  reqteam: String,
  selectedteam: String,
  reqtype: String,
  file: String,
  shortdesc: String,
  selectedshortdesc: String,
  automationdesc: String,
  workinstructiondesc: String,
  techdetailsdesc: String,
  business:String,
  poc:String,
  time: String,
  cost: String,
  effort: String,
  comments: String,
  eta: String,
  status: String
}
